# Generated by Django 2.0 on 2019-01-24 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='DoneDutyTasksGenarator',
            fields=[
                ('task_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ExaminationSystem',
            fields=[
                ('examination_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('examination_level', models.CharField(choices=[('UG', 'Undergraduate'), ('PG', 'Postgraduate'), ('PD', 'Doctorate'), ('EX', 'Executive Program')], max_length=2)),
                ('semester_selection', models.CharField(choices=[('1-1', '1st Year - 1st Semester'), ('1-2', '1st Year - 2nd Semester'), ('2-1', '2nd Year - 1st Semester'), ('2-2', '2nd Year - 2nd Semester'), ('3-1', '3rd Year - 1st Semester'), ('3-2', '3rd Year - 2nd Semester'), ('4-1', '4th Year - 1st Semester'), ('4-2', '4th Year - 2nd Semester')], max_length=3)),
                ('examination_year', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='ExamProposal',
            fields=[
                ('exam_proposal_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='GenarateBillOfTheExaminer',
            fields=[
                ('bill_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('examination_grade', models.ForeignKey(db_column='examination_level', on_delete=django.db.models.deletion.CASCADE, related_name='ExaminationGradeBG', to='main.ExaminationSystem')),
                ('examination_semester', models.ForeignKey(db_column='semester_selection', on_delete=django.db.models.deletion.CASCADE, related_name='ExaminationSemesterBG', to='main.ExaminationSystem')),
                ('examination_year_of_the_exam', models.ForeignKey(db_column='examination_year', on_delete=django.db.models.deletion.CASCADE, related_name='ExaminationYearBG', to='main.ExaminationSystem')),
            ],
        ),
        migrations.CreateModel(
            name='LabExamRoutineGenarator',
            fields=[
                ('lab_exam_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('lab_exam_date_select', models.DateField()),
                ('lab_exam_start_time_select', models.TimeField()),
                ('lab_exam_end_time_select', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='LabExamTabulatorGenarator',
            fields=[
                ('lab_exam_tabulator_list_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectCreation',
            fields=[
                ('sibject_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('course_code', models.IntegerField()),
                ('course_name', models.CharField(max_length=30)),
                ('course_credit', models.CharField(choices=[('0.75', '0.75 Credit'), ('1.00', '1.00 Credit'), ('1.50', '1.50 Credit'), ('2.00', '2.00 Credit'), ('3.00', '3.00 Credit'), ('4.00', '4.00 Credit')], max_length=1)),
                ('select_department', models.ForeignKey(db_column='dept_id', on_delete=django.db.models.deletion.CASCADE, to='main.Department')),
                ('select_semester_year', models.ForeignKey(db_column='semester_selection', on_delete=django.db.models.deletion.CASCADE, to='main.ExaminationSystem')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('teacher_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('teacher_name', models.CharField(max_length=40)),
                ('teacher_shortCode', models.CharField(max_length=5)),
                ('teacher_designation', models.CharField(max_length=20)),
                ('teachers_university', models.CharField(max_length=20)),
                ('dept_id', models.ForeignKey(db_column='dept_id', on_delete=django.db.models.deletion.CASCADE, to='main.Department')),
            ],
        ),
        migrations.CreateModel(
            name='TheoryExamRoutineGenarator',
            fields=[
                ('theory_exam_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('theory_exam_date_select', models.DateField()),
                ('theory_exam_start_time_select', models.TimeField()),
                ('theory_exam_end_time_select', models.TimeField()),
                ('theory_exam_course_code_select', models.ForeignKey(db_column='course_code', on_delete=django.db.models.deletion.CASCADE, related_name='theoryExamCode', to='main.SubjectCreation')),
                ('theory_exam_course_credit_select', models.ForeignKey(db_column='course_credit', on_delete=django.db.models.deletion.CASCADE, related_name='theoryExamCredit', to='main.SubjectCreation')),
                ('theory_exam_course_name_select', models.ForeignKey(db_column='course_name', on_delete=django.db.models.deletion.CASCADE, related_name='theoryExamName', to='main.SubjectCreation')),
            ],
        ),
        migrations.CreateModel(
            name='TheoryExamTabulatorGenarator',
            fields=[
                ('theory_exam_tabulator_list_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('select_exam', models.ManyToManyField(to='main.TheoryExamRoutineGenarator')),
                ('select_first_examiner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='FirstExaminerTheory', to='main.TeacherProfile')),
                ('select_secound_examiner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='SecoundExaminerTheory', to='main.TeacherProfile')),
                ('select_third_examiner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ThirdExaminerTheory', to='main.TeacherProfile')),
            ],
        ),
        migrations.CreateModel(
            name='VivaVoceExamRoutineGenarator',
            fields=[
                ('viva_voce_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('viva_voce_date_select', models.DateField()),
                ('viva_voce_start_time_select', models.TimeField()),
                ('viva_voce_end_time_select', models.TimeField()),
                ('viva_voce_course_code_select', models.ForeignKey(db_column='course_code', on_delete=django.db.models.deletion.CASCADE, related_name='VivaVoceExamCode', to='main.SubjectCreation')),
                ('viva_voce_course_credit_select', models.ForeignKey(db_column='course_credit', on_delete=django.db.models.deletion.CASCADE, related_name='VivaVoceExamCredit', to='main.SubjectCreation')),
                ('viva_voce_course_name_select', models.ForeignKey(db_column='course_name', on_delete=django.db.models.deletion.CASCADE, related_name='VivaVoceExamName', to='main.SubjectCreation')),
            ],
        ),
        migrations.CreateModel(
            name='VivaVoceExamTabulatorGenarator',
            fields=[
                ('viva_voce_tabulator_list_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('select_exam', models.ManyToManyField(to='main.TheoryExamRoutineGenarator')),
                ('select_first_examiner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='FirstExaminerVivaVoce', to='main.TeacherProfile')),
                ('select_secound_examiner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='SecoundExaminerVivaVoce', to='main.TeacherProfile')),
                ('select_third_examiner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ThirdExaminerVivaVoce', to='main.TeacherProfile')),
            ],
        ),
        migrations.AddField(
            model_name='labexamtabulatorgenarator',
            name='select_exam',
            field=models.ManyToManyField(to='main.TheoryExamRoutineGenarator'),
        ),
        migrations.AddField(
            model_name='labexamtabulatorgenarator',
            name='select_first_examiner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='FirstExaminerLab', to='main.TeacherProfile'),
        ),
        migrations.AddField(
            model_name='labexamtabulatorgenarator',
            name='select_secound_examiner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='SecoundExaminerLab', to='main.TeacherProfile'),
        ),
        migrations.AddField(
            model_name='labexamtabulatorgenarator',
            name='select_third_examiner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ThirdExaminerLab', to='main.TeacherProfile'),
        ),
        migrations.AddField(
            model_name='labexamroutinegenarator',
            name='lab_exam_course_code_select',
            field=models.ForeignKey(db_column='course_code', on_delete=django.db.models.deletion.CASCADE, related_name='labExamCode', to='main.SubjectCreation'),
        ),
        migrations.AddField(
            model_name='labexamroutinegenarator',
            name='lab_exam_course_credit_select',
            field=models.ForeignKey(db_column='course_credit', on_delete=django.db.models.deletion.CASCADE, related_name='labExamCredit', to='main.SubjectCreation'),
        ),
        migrations.AddField(
            model_name='labexamroutinegenarator',
            name='lab_exam_course_name_select',
            field=models.ForeignKey(db_column='course_name', on_delete=django.db.models.deletion.CASCADE, related_name='labExamName', to='main.SubjectCreation'),
        ),
        migrations.AddField(
            model_name='genaratebilloftheexaminer',
            name='examiner_name',
            field=models.ForeignKey(db_column='teacher_name', on_delete=django.db.models.deletion.CASCADE, to='main.TeacherProfile'),
        ),
        migrations.AddField(
            model_name='examproposal',
            name='commitee_cheaf',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ChiefMember', to='main.TeacherProfile'),
        ),
        migrations.AddField(
            model_name='examproposal',
            name='committee_member_one',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='FirstMember', to='main.TeacherProfile'),
        ),
        migrations.AddField(
            model_name='examproposal',
            name='committee_member_two',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='SecoundMember', to='main.TeacherProfile'),
        ),
        migrations.AddField(
            model_name='examproposal',
            name='exam_of_the_department',
            field=models.ManyToManyField(to='main.Department'),
        ),
        migrations.AddField(
            model_name='examproposal',
            name='proposed_examination_to_take',
            field=models.ManyToManyField(to='main.ExaminationSystem'),
        ),
        migrations.AddField(
            model_name='donedutytasksgenarator',
            name='examination_grade',
            field=models.ForeignKey(db_column='examination_level', on_delete=django.db.models.deletion.CASCADE, related_name='ExaminationGradeTG', to='main.ExaminationSystem'),
        ),
        migrations.AddField(
            model_name='donedutytasksgenarator',
            name='examination_semester',
            field=models.ForeignKey(db_column='semester_selection', on_delete=django.db.models.deletion.CASCADE, related_name='ExaminationSemesterTG', to='main.ExaminationSystem'),
        ),
        migrations.AddField(
            model_name='donedutytasksgenarator',
            name='examination_year_of_the_exam',
            field=models.ForeignKey(db_column='examination_year', on_delete=django.db.models.deletion.CASCADE, related_name='ExaminationYearTG', to='main.ExaminationSystem'),
        ),
        migrations.AddField(
            model_name='donedutytasksgenarator',
            name='examiner_name',
            field=models.ForeignKey(db_column='teacher_name', on_delete=django.db.models.deletion.CASCADE, to='main.TeacherProfile'),
        ),
    ]
