# Generated by Django 2.0 on 2019-01-24 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190124_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectcreation',
            name='course_credit',
            field=models.CharField(choices=[('.75C', '0.75 Credit'), ('1.0C', '1.00 Credit'), ('1.5C', '1.50 Credit'), ('2.0C', '2.00 Credit'), ('3.0C', '3.00 Credit'), ('4.0C', '4.00 Credit')], max_length=4),
        ),
    ]
