# Generated by Django 2.0 on 2019-01-24 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190124_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectcreation',
            name='course_code',
            field=models.CharField(max_length=5),
        ),
    ]
