# Generated by Django 2.0 on 2019-01-25 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190124_1734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjectcreation',
            old_name='sibject_id',
            new_name='course_id',
        ),
        migrations.RemoveField(
            model_name='labexamroutinegenarator',
            name='lab_exam_course_credit_select',
        ),
        migrations.RemoveField(
            model_name='labexamroutinegenarator',
            name='lab_exam_course_name_select',
        ),
        migrations.RemoveField(
            model_name='subjectcreation',
            name='course_code',
        ),
        migrations.RemoveField(
            model_name='theoryexamroutinegenarator',
            name='theory_exam_course_credit_select',
        ),
        migrations.RemoveField(
            model_name='theoryexamroutinegenarator',
            name='theory_exam_course_name_select',
        ),
        migrations.RemoveField(
            model_name='vivavoceexamroutinegenarator',
            name='viva_voce_course_credit_select',
        ),
        migrations.RemoveField(
            model_name='vivavoceexamroutinegenarator',
            name='viva_voce_course_name_select',
        ),
        migrations.AlterField(
            model_name='department',
            name='dept_id',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='labexamroutinegenarator',
            name='lab_exam_course_code_select',
        ),
        migrations.AddField(
            model_name='labexamroutinegenarator',
            name='lab_exam_course_code_select',
            field=models.ManyToManyField(to='main.SubjectCreation'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='teacher_id',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='teacher_shortCode',
            field=models.CharField(max_length=10),
        ),
        migrations.RemoveField(
            model_name='theoryexamroutinegenarator',
            name='theory_exam_course_code_select',
        ),
        migrations.AddField(
            model_name='theoryexamroutinegenarator',
            name='theory_exam_course_code_select',
            field=models.ManyToManyField(to='main.SubjectCreation'),
        ),
        migrations.RemoveField(
            model_name='vivavoceexamroutinegenarator',
            name='viva_voce_course_code_select',
        ),
        migrations.AddField(
            model_name='vivavoceexamroutinegenarator',
            name='viva_voce_course_code_select',
            field=models.ManyToManyField(to='main.SubjectCreation'),
        ),
    ]
